"""empty message

Revision ID: 0d63025b9165
Revises: c3570a189b2f
Create Date: 2019-03-23 08:56:33.585527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d63025b9165'
down_revision = 'c3570a189b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('status', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing', 'status')
    # ### end Alembic commands ###
