"""empty message

Revision ID: 7a311b8b1c16
Revises: e4106358fdd0
Create Date: 2019-02-23 21:02:44.872591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a311b8b1c16'
down_revision = 'e4106358fdd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phrases', sa.Column('class_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phrases', 'class_id')
    # ### end Alembic commands ###
