"""empty message

Revision ID: adee59d869c2
Revises: ec6e7d80c483
Create Date: 2019-02-22 13:16:16.871703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adee59d869c2'
down_revision = 'ec6e7d80c483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alphabet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('image_path', sa.String(length=200), nullable=True),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alphabet_file_name'), 'alphabet', ['file_name'], unique=True)
    op.drop_index('ix_content_file_name', table_name='content')
    op.drop_table('content')
    op.add_column('phrases', sa.Column('image_path', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phrases', 'image_path')
    op.create_table('content',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('file_name', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_content_file_name', 'content', ['file_name'], unique=1)
    op.drop_index(op.f('ix_alphabet_file_name'), table_name='alphabet')
    op.drop_table('alphabet')
    # ### end Alembic commands ###
