"""empty message

Revision ID: c3570a189b2f
Revises: 
Create Date: 2019-03-22 08:40:38.263461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3570a189b2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alphabet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('image_path', sa.String(length=200), nullable=True),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alphabet_file_name'), 'alphabet', ['file_name'], unique=True)
    op.create_table('billing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_billed', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('poll_url', sa.String(length=2000), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('background_image', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('background_image', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phrases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(length=200), nullable=True),
    sa.Column('image_path', sa.String(length=200), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phrases_file_name'), 'phrases', ['file_name'], unique=True)
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(length=200), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_section_file_name'), 'section', ['file_name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('surname', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('social_id', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('social_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index(op.f('ix_section_file_name'), table_name='section')
    op.drop_table('section')
    op.drop_index(op.f('ix_phrases_file_name'), table_name='phrases')
    op.drop_table('phrases')
    op.drop_table('course')
    op.drop_table('classes')
    op.drop_table('billing')
    op.drop_index(op.f('ix_alphabet_file_name'), table_name='alphabet')
    op.drop_table('alphabet')
    # ### end Alembic commands ###
